ServerEvents.recipes(event => {
    event.custom({
        "type": "multiblocklibes:structure",
        "structure_id": "blast",
        "controller_id": "multiblocklibes:test_controller",
        "pattern": [
            [1, 0, 0, ["minecraft:oxidized_cut_copper", "multiblocklibes:test_item_port_in", "multiblocklibes:test_item_port_ou", "multiblocklibes:test_fluid_port_in", "multiblocklibes:test_fluid_port_ou", "multiblocklibes:test_fe_port"]],
            [-1, 0, 0, ["minecraft:oxidized_cut_copper", "multiblocklibes:test_item_port_in", "multiblocklibes:test_item_port_ou", "multiblocklibes:test_fluid_port_in", "multiblocklibes:test_fluid_port_ou", "multiblocklibes:test_fe_port"]],
            [1, 0, 1, ["minecraft:oxidized_cut_copper", "multiblocklibes:test_item_port_in", "multiblocklibes:test_item_port_ou", "multiblocklibes:test_fluid_port_in", "multiblocklibes:test_fluid_port_ou", "multiblocklibes:test_fe_port"]],
            [-1, 0, 1, ["minecraft:oxidized_cut_copper", "multiblocklibes:test_item_port_in", "multiblocklibes:test_item_port_ou", "multiblocklibes:test_fluid_port_in", "multiblocklibes:test_fluid_port_ou", "multiblocklibes:test_fe_port"]],
            [1, 0, 2, ["minecraft:oxidized_cut_copper", "multiblocklibes:test_item_port_in", "multiblocklibes:test_item_port_ou", "multiblocklibes:test_fluid_port_in", "multiblocklibes:test_fluid_port_ou", "multiblocklibes:test_fe_port"]],
            [0, 0, 2, ["minecraft:oxidized_cut_copper", "multiblocklibes:test_item_port_in", "multiblocklibes:test_item_port_ou", "multiblocklibes:test_fluid_port_in", "multiblocklibes:test_fluid_port_ou", "multiblocklibes:test_fe_port"]],
            [-1, 0, 2, ["minecraft:oxidized_cut_copper", "multiblocklibes:test_item_port_in", "multiblocklibes:test_item_port_ou", "multiblocklibes:test_fluid_port_in", "multiblocklibes:test_fluid_port_ou", "multiblocklibes:test_fe_port"]],
            [0, 0, 1, ["minecraft:oxidized_cut_copper", "multiblocklibes:test_item_port_in", "multiblocklibes:test_item_port_ou", "multiblocklibes:test_fluid_port_in", "multiblocklibes:test_fluid_port_ou", "multiblocklibes:test_fe_port"]],

            [1, 3, 0, ["minecraft:oxidized_cut_copper", "multiblocklibes:test_item_port_in", "multiblocklibes:test_item_port_ou", "multiblocklibes:test_fluid_port_in", "multiblocklibes:test_fluid_port_ou", "multiblocklibes:test_fe_port"]],
            [0, 3, 0, ["minecraft:oxidized_cut_copper", "multiblocklibes:test_item_port_in", "multiblocklibes:test_item_port_ou", "multiblocklibes:test_fluid_port_in", "multiblocklibes:test_fluid_port_ou", "multiblocklibes:test_fe_port"]],
            [-1, 3, 0, ["minecraft:oxidized_cut_copper", "multiblocklibes:test_item_port_in", "multiblocklibes:test_item_port_ou", "multiblocklibes:test_fluid_port_in", "multiblocklibes:test_fluid_port_ou", "multiblocklibes:test_fe_port"]],
            [1, 3, 1, ["minecraft:oxidized_cut_copper", "multiblocklibes:test_item_port_in", "multiblocklibes:test_item_port_ou", "multiblocklibes:test_fluid_port_in", "multiblocklibes:test_fluid_port_ou", "multiblocklibes:test_fe_port"]],
            [-1, 3, 1, ["minecraft:oxidized_cut_copper", "multiblocklibes:test_item_port_in", "multiblocklibes:test_item_port_ou", "multiblocklibes:test_fluid_port_in", "multiblocklibes:test_fluid_port_ou", "multiblocklibes:test_fe_port"]],
            [1, 3, 2, ["minecraft:oxidized_cut_copper", "multiblocklibes:test_item_port_in", "multiblocklibes:test_item_port_ou", "multiblocklibes:test_fluid_port_in", "multiblocklibes:test_fluid_port_ou", "multiblocklibes:test_fe_port"]],
            [0, 3, 2, ["minecraft:oxidized_cut_copper", "multiblocklibes:test_item_port_in", "multiblocklibes:test_item_port_ou", "multiblocklibes:test_fluid_port_in", "multiblocklibes:test_fluid_port_ou", "multiblocklibes:test_fe_port"]],
            [-1, 3, 2, ["minecraft:oxidized_cut_copper", "multiblocklibes:test_item_port_in", "multiblocklibes:test_item_port_ou", "multiblocklibes:test_fluid_port_in", "multiblocklibes:test_fluid_port_ou", "multiblocklibes:test_fe_port"]],

            [0, 1, 0, ["minecraft:diamond_block", "minecraft:emerald_block"]],
            [1, 1, 0, ["minecraft:diamond_block", "minecraft:emerald_block"]],
            [-1, 1, 0, ["minecraft:diamond_block", "minecraft:emerald_block"]],
            [1, 1, 1, ["minecraft:diamond_block", "minecraft:emerald_block"]],
            [-1, 1, 1, ["minecraft:diamond_block", "minecraft:emerald_block"]],
            [1, 1, 2, ["minecraft:diamond_block", "minecraft:emerald_block"]],
            [0, 1, 2, ["minecraft:diamond_block", "minecraft:emerald_block"]],
            [-1, 1, 2, ["minecraft:diamond_block", "minecraft:emerald_block"]],

            [0, 2, 0, ["minecraft:diamond_block", "minecraft:emerald_block"]],
            [1, 2, 0, ["minecraft:diamond_block", "minecraft:emerald_block"]],
            [-1, 2, 0, ["minecraft:diamond_block", "minecraft:emerald_block"]],
            [1, 2, 1, ["minecraft:diamond_block", "minecraft:emerald_block"]],
            [-1, 2, 1, ["minecraft:diamond_block", "minecraft:emerald_block"]],
            [1, 2, 2, ["minecraft:diamond_block", "minecraft:emerald_block"]],
            [0, 2, 2, ["minecraft:diamond_block", "minecraft:emerald_block"]],
            [-1, 2, 2, ["minecraft:diamond_block", "minecraft:emerald_block"]],

            [0, 3, 1, ["multiblocklibes:test_waste"]]
        ],
        "requirements": [
            {
                "id": "same_block_structure_requirement",
                "property": [
                    [0, 1, 0],
                    [1, 1, 0],
                    [-1, 1, 0],
                    [1, 1, 1],
                    [-1, 1, 1],
                    [1, 1, 2],
                    [0, 1, 2],
                    [-1, 1, 2],

                    [0, 2, 0],
                    [1, 2, 0],
                    [-1, 2, 0],
                    [1, 2, 1],
                    [-1, 2, 1],
                    [1, 2, 2],
                    [0, 2, 2],
                    [-1, 2, 2]
                ]
            },
            {
                "id": "right_count_blocks_structure_requirement",
                "property": [
                    ["multiblocklibes:test_item_port_in"],
                    1
                ]
            },
            {
                "id": "right_count_blocks_structure_requirement",
                "property": [
                    ["multiblocklibes:test_item_port_ou"],
                    1
                ]
            },
            {
                "id": "right_count_blocks_structure_requirement",
                "property": [
                    ["multiblocklibes:test_fluid_port_in"],
                    1
                ]
            },
            {
                "id": "right_count_blocks_structure_requirement",
                "property": [
                    ["multiblocklibes:test_fluid_port_ou"],
                    1
                ]
            },
            {
                "id": "right_count_blocks_structure_requirement",
                "property": [
                    ["multiblocklibes:test_fe_port"],
                    1
                ]
            }
        ]
    })

    event.custom({
        "type": "multiblocklibes:recipe",
        "time": 100,
        "recipe_id": "blast_revipe_test",
        "structure_id": "blast",
        "requirements": [
            {
                "id": "item_recipe_requirement",
                "property": [
                    "input",
                    "minecraft:iron_ingot",
                    3
                ]
            },
            {
                "id": "item_recipe_requirement",
                "property": [
                    "output",
                    "minecraft:netherite_ingot",
                    1,
                    ["multiblocklibes:test_item_port_ou"]
                ]
            },
            {
                "id": "item_recipe_requirement",
                "property": [
                    "output",
                    "minecraft:gunpowder",
                    2,
                    ["multiblocklibes:test_waste"]
                ]
            },
            {
                "id": "fe_recipe_requirement",
                "property": [
                    "input",
                    5
                ]
            },
            {
                "id": "desc_recipe_requirement",
                "property": [
                    "nauxy",
                    "s"
                ]
            }
        ]
    })

    event.custom({
        "type": "multiblocklibes:structure",
        "structure_id": "xddd",
        "controller_id": "multiblocklibes:test_controller",
        "pattern": [
            [-4, 0, 0, ["minecraft:oxidized_cut_copper"]],
            [-4, 0, 1, ["minecraft:oxidized_cut_copper"]],
            [-4, 0, 2, ["minecraft:oxidized_cut_copper"]],
            [-4, 0, 3, ["minecraft:oxidized_cut_copper"]],
            [-4, 0, 4, ["minecraft:oxidized_cut_copper"]],
            [-4, 0, 5, ["minecraft:oxidized_cut_copper"]],
            [-4, 0, 6, ["minecraft:oxidized_cut_copper"]],
            [-4, 0, 7, ["minecraft:oxidized_cut_copper"]],
            [-4, 0, 8, ["minecraft:oxidized_cut_copper"]],
            [-4, 5, 0, ["minecraft:lantern"]],
            [-4, 5, 8, ["minecraft:lantern"]],
            [-4, 6, 0, ["minecraft:stone"]],
            [-4, 6, 1, ["minecraft:stone"]],
            [-4, 6, 7, ["minecraft:stone"]],
            [-4, 6, 8, ["minecraft:stone"]],
            [-3, 0, 0, ["minecraft:oxidized_cut_copper"]],
            [-3, 0, 1, ["minecraft:oxidized_cut_copper"]],
            [-3, 0, 2, ["minecraft:oxidized_cut_copper"]],
            [-3, 0, 3, ["minecraft:oxidized_cut_copper"]],
            [-3, 0, 4, ["minecraft:oxidized_cut_copper"]],
            [-3, 0, 5, ["minecraft:oxidized_cut_copper"]],
            [-3, 0, 6, ["minecraft:oxidized_cut_copper"]],
            [-3, 0, 7, ["minecraft:oxidized_cut_copper"]],
            [-3, 0, 8, ["minecraft:oxidized_cut_copper"]],
            [-3, 1, 2, ["minecraft:blast_furnace"]],
            [-3, 1, 3, ["minecraft:blast_furnace"]],
            [-3, 1, 4, ["minecraft:blast_furnace"]],
            [-3, 1, 5, ["minecraft:blast_furnace"]],
            [-3, 1, 6, ["minecraft:blast_furnace"]],
            [-3, 1, 7, ["minecraft:end_rod"]],
            [-3, 6, 0, ["minecraft:stone"]],
            [-3, 6, 1, ["minecraft:stone"]],
            [-3, 6, 2, ["minecraft:stone"]],
            [-3, 6, 6, ["minecraft:stone"]],
            [-3, 6, 7, ["minecraft:stone"]],
            [-3, 6, 8, ["minecraft:stone"]],
            [-2, 0, 0, ["multiblocklibes:test_item_port_ou"]],
            [-2, 0, 1, ["minecraft:oxidized_cut_copper"]],
            [-2, 0, 2, ["minecraft:oxidized_cut_copper"]],
            [-2, 0, 3, ["minecraft:oxidized_cut_copper"]],
            [-2, 0, 4, ["minecraft:oxidized_cut_copper"]],
            [-2, 0, 5, ["minecraft:oxidized_cut_copper"]],
            [-2, 0, 6, ["minecraft:oxidized_cut_copper"]],
            [-2, 0, 7, ["minecraft:oxidized_cut_copper"]],
            [-2, 0, 8, ["minecraft:oxidized_cut_copper"]],
            [-2, 1, 0, ["multiblocklibes:test_item_port_ou"]],
            [-2, 1, 1, ["minecraft:oxidized_cut_copper"]],
            [-2, 1, 2, ["minecraft:andesite"]],
            [-2, 1, 3, ["minecraft:andesite"]],
            [-2, 1, 4, ["minecraft:andesite"]],
            [-2, 1, 5, ["minecraft:andesite"]],
            [-2, 1, 6, ["minecraft:andesite"]],
            [-2, 1, 7, ["minecraft:crying_obsidian"]],
            [-2, 2, 1, ["minecraft:stonecutter"]],
            [-2, 2, 2, ["minecraft:iron_chain"]],
            [-2, 2, 3, ["minecraft:conduit"]],
            [-2, 2, 4, ["minecraft:lodestone"]],
            [-2, 2, 5, ["minecraft:conduit"]],
            [-2, 2, 6, ["minecraft:iron_chain"]],
            [-2, 3, 2, ["minecraft:iron_chain"]],
            [-2, 3, 6, ["minecraft:iron_chain"]],
            [-2, 4, 2, ["minecraft:redstone_block"]],
            [-2, 4, 3, ["minecraft:redstone_block"]],
            [-2, 4, 5, ["minecraft:redstone_block"]],
            [-2, 4, 6, ["minecraft:redstone_block"]],
            [-2, 6, 1, ["minecraft:stone"]],
            [-2, 6, 2, ["minecraft:stone"]],
            [-2, 6, 3, ["minecraft:stone"]],
            [-2, 6, 5, ["minecraft:stone"]],
            [-2, 6, 6, ["minecraft:stone"]],
            [-2, 6, 7, ["minecraft:stone"]],
            [-1, 0, 0, ["multiblocklibes:test_item_port_ou"]],
            [-1, 0, 1, ["minecraft:oxidized_cut_copper"]],
            [-1, 0, 2, ["minecraft:oxidized_cut_copper"]],
            [-1, 0, 3, ["minecraft:oxidized_cut_copper"]],
            [-1, 0, 4, ["minecraft:oxidized_cut_copper"]],
            [-1, 0, 5, ["minecraft:oxidized_cut_copper"]],
            [-1, 0, 6, ["minecraft:oxidized_cut_copper"]],
            [-1, 0, 7, ["minecraft:oxidized_cut_copper"]],
            [-1, 0, 8, ["minecraft:oxidized_cut_copper"]],
            [-1, 1, 0, ["multiblocklibes:test_item_port_ou"]],
            [-1, 1, 1, ["minecraft:oxidized_cut_copper"]],
            [-1, 1, 2, ["minecraft:andesite"]],
            [-1, 1, 3, ["minecraft:andesite"]],
            [-1, 1, 4, ["minecraft:andesite"]],
            [-1, 1, 5, ["minecraft:andesite"]],
            [-1, 1, 6, ["minecraft:andesite"]],
            [-1, 1, 7, ["minecraft:crying_obsidian"]],
            [-1, 2, 1, ["minecraft:stonecutter"]],
            [-1, 2, 3, ["minecraft:redstone_torch"]],
            [-1, 2, 4, ["minecraft:redstone_torch"]],
            [-1, 2, 5, ["minecraft:redstone_torch"]],
            [-1, 2, 6, ["minecraft:prismarine"]],
            [-1, 3, 3, ["minecraft:oak_planks"]],
            [-1, 3, 4, ["minecraft:oak_planks"]],
            [-1, 3, 5, ["minecraft:oak_planks"]],
            [-1, 3, 6, ["minecraft:ancient_debris"]],
            [-1, 4, 2, ["minecraft:redstone_block"]],
            [-1, 4, 3, ["minecraft:glass"]],
            [-1, 4, 4, ["minecraft:glass"]],
            [-1, 4, 5, ["minecraft:glass"]],
            [-1, 4, 6, ["minecraft:redstone_block"]],
            [-1, 5, 3, ["minecraft:glass"]],
            [-1, 5, 4, ["minecraft:glass"]],
            [-1, 5, 5, ["minecraft:glass"]],
            [-1, 6, 2, ["minecraft:stone"]],
            [-1, 6, 3, ["minecraft:stone"]],
            [-1, 6, 4, ["minecraft:stone"]],
            [-1, 6, 5, ["minecraft:stone"]],
            [-1, 6, 6, ["minecraft:stone"]],
            [0, 0, 1, ["minecraft:oxidized_cut_copper"]],
            [0, 0, 2, ["minecraft:oxidized_cut_copper"]],
            [0, 0, 3, ["minecraft:oxidized_cut_copper"]],
            [0, 0, 4, ["minecraft:oxidized_cut_copper"]],
            [0, 0, 5, ["minecraft:oxidized_cut_copper"]],
            [0, 0, 6, ["minecraft:oxidized_cut_copper"]],
            [0, 0, 7, ["minecraft:oxidized_cut_copper"]],
            [0, 0, 8, ["minecraft:oxidized_cut_copper"]],
            [0, 1, 1, ["minecraft:redstone_lamp"]],
            [0, 1, 2, ["minecraft:andesite"]],
            [0, 1, 3, ["minecraft:andesite"]],
            [0, 1, 4, ["minecraft:andesite"]],
            [0, 1, 5, ["minecraft:andesite"]],
            [0, 1, 6, ["minecraft:andesite"]],
            [0, 1, 7, ["minecraft:crying_obsidian"]],
            [0, 2, 1, ["minecraft:waxed_lightning_rod"]],
            [0, 2, 3, ["minecraft:redstone_torch"]],
            [0, 2, 4, ["minecraft:redstone_torch"]],
            [0, 2, 5, ["minecraft:redstone_torch"]],
            [0, 2, 6, ["minecraft:prismarine"]],
            [0, 3, 1, ["minecraft:waxed_lightning_rod"]],
            [0, 3, 3, ["minecraft:oak_planks"]],
            [0, 3, 4, ["minecraft:oak_planks"]],
            [0, 3, 5, ["minecraft:oak_planks"]],
            [0, 4, 1, ["minecraft:waxed_lightning_rod"]],
            [0, 4, 3, ["minecraft:glass"]],
            [0, 4, 5, ["minecraft:glass"]],
            [0, 4, 6, ["minecraft:ancient_debris"]],
            [0, 5, 1, ["minecraft:waxed_lightning_rod"]],
            [0, 5, 3, ["minecraft:glass"]],
            [0, 5, 5, ["minecraft:glass"]],
            [0, 5, 6, ["minecraft:ancient_debris"]],
            [0, 6, 1, ["minecraft:spruce_trapdoor"]],
            [0, 6, 2, ["minecraft:spruce_trapdoor"]],
            [0, 6, 3, ["minecraft:stone"]],
            [0, 6, 4, ["minecraft:stone"]],
            [0, 6, 5, ["minecraft:stone"]],
            [0, 6, 6, ["minecraft:ancient_debris"]],
            [1, 0, 0, ["multiblocklibes:test_item_port_in"]],
            [1, 0, 1, ["minecraft:oxidized_cut_copper"]],
            [1, 0, 2, ["minecraft:oxidized_cut_copper"]],
            [1, 0, 3, ["minecraft:oxidized_cut_copper"]],
            [1, 0, 4, ["minecraft:oxidized_cut_copper"]],
            [1, 0, 5, ["minecraft:oxidized_cut_copper"]],
            [1, 0, 6, ["minecraft:oxidized_cut_copper"]],
            [1, 0, 7, ["minecraft:oxidized_cut_copper"]],
            [1, 0, 8, ["minecraft:oxidized_cut_copper"]],
            [1, 1, 0, ["multiblocklibes:test_item_port_in"]],
            [1, 1, 1, ["minecraft:oxidized_cut_copper"]],
            [1, 1, 2, ["minecraft:andesite"]],
            [1, 1, 3, ["minecraft:andesite"]],
            [1, 1, 4, ["minecraft:andesite"]],
            [1, 1, 5, ["minecraft:andesite"]],
            [1, 1, 6, ["minecraft:andesite"]],
            [1, 1, 7, ["minecraft:crying_obsidian"]],
            [1, 2, 1, ["minecraft:stonecutter"]],
            [1, 2, 3, ["minecraft:redstone_torch"]],
            [1, 2, 4, ["minecraft:redstone_torch"]],
            [1, 2, 5, ["minecraft:redstone_torch"]],
            [1, 2, 6, ["minecraft:prismarine"]],
            [1, 3, 3, ["minecraft:oak_planks"]],
            [1, 3, 4, ["minecraft:oak_planks"]],
            [1, 3, 5, ["minecraft:oak_planks"]],
            [1, 3, 6, ["minecraft:ancient_debris"]],
            [1, 4, 2, ["minecraft:redstone_block"]],
            [1, 4, 3, ["minecraft:glass"]],
            [1, 4, 4, ["minecraft:glass"]],
            [1, 4, 5, ["minecraft:glass"]],
            [1, 4, 6, ["minecraft:redstone_block"]],
            [1, 5, 3, ["minecraft:glass"]],
            [1, 5, 4, ["minecraft:glass"]],
            [1, 5, 5, ["minecraft:glass"]],
            [1, 6, 2, ["minecraft:stone"]],
            [1, 6, 3, ["minecraft:stone"]],
            [1, 6, 4, ["minecraft:stone"]],
            [1, 6, 5, ["minecraft:stone"]],
            [1, 6, 6, ["minecraft:stone"]],
            [2, 0, 0, ["multiblocklibes:test_item_port_in"]],
            [2, 0, 1, ["minecraft:oxidized_cut_copper"]],
            [2, 0, 2, ["minecraft:oxidized_cut_copper"]],
            [2, 0, 3, ["minecraft:oxidized_cut_copper"]],
            [2, 0, 4, ["minecraft:oxidized_cut_copper"]],
            [2, 0, 5, ["minecraft:oxidized_cut_copper"]],
            [2, 0, 6, ["minecraft:oxidized_cut_copper"]],
            [2, 0, 7, ["minecraft:oxidized_cut_copper"]],
            [2, 0, 8, ["minecraft:oxidized_cut_copper"]],
            [2, 1, 0, ["multiblocklibes:test_item_port_in"]],
            [2, 1, 1, ["minecraft:oxidized_cut_copper"]],
            [2, 1, 2, ["minecraft:andesite"]],
            [2, 1, 3, ["minecraft:andesite"]],
            [2, 1, 4, ["minecraft:andesite"]],
            [2, 1, 5, ["minecraft:andesite"]],
            [2, 1, 6, ["minecraft:andesite"]],
            [2, 1, 7, ["minecraft:crying_obsidian"]],
            [2, 2, 1, ["minecraft:stonecutter"]],
            [2, 2, 2, ["minecraft:iron_chain"]],
            [2, 2, 3, ["minecraft:conduit"]],
            [2, 2, 4, ["minecraft:lodestone"]],
            [2, 2, 5, ["minecraft:conduit"]],
            [2, 2, 6, ["minecraft:iron_chain"]],
            [2, 3, 2, ["minecraft:iron_chain"]],
            [2, 3, 6, ["minecraft:iron_chain"]],
            [2, 4, 2, ["minecraft:redstone_block"]],
            [2, 4, 3, ["minecraft:redstone_block"]],
            [2, 4, 5, ["minecraft:redstone_block"]],
            [2, 4, 6, ["minecraft:redstone_block"]],
            [2, 6, 1, ["minecraft:stone"]],
            [2, 6, 2, ["minecraft:stone"]],
            [2, 6, 3, ["minecraft:stone"]],
            [2, 6, 5, ["minecraft:stone"]],
            [2, 6, 6, ["minecraft:stone"]],
            [2, 6, 7, ["minecraft:stone"]],
            [3, 0, 0, ["minecraft:oxidized_cut_copper"]],
            [3, 0, 1, ["minecraft:oxidized_cut_copper"]],
            [3, 0, 2, ["minecraft:oxidized_cut_copper"]],
            [3, 0, 3, ["minecraft:oxidized_cut_copper"]],
            [3, 0, 4, ["minecraft:oxidized_cut_copper"]],
            [3, 0, 5, ["minecraft:oxidized_cut_copper"]],
            [3, 0, 6, ["minecraft:oxidized_cut_copper"]],
            [3, 0, 7, ["minecraft:oxidized_cut_copper"]],
            [3, 0, 8, ["minecraft:oxidized_cut_copper"]],
            [3, 1, 2, ["minecraft:blast_furnace"]],
            [3, 1, 3, ["minecraft:blast_furnace"]],
            [3, 1, 4, ["minecraft:blast_furnace"]],
            [3, 1, 5, ["minecraft:blast_furnace"]],
            [3, 1, 6, ["minecraft:blast_furnace"]],
            [3, 1, 7, ["minecraft:end_rod"]],
            [3, 6, 0, ["minecraft:stone"]],
            [3, 6, 1, ["minecraft:stone"]],
            [3, 6, 2, ["minecraft:stone"]],
            [3, 6, 6, ["minecraft:stone"]],
            [3, 6, 7, ["minecraft:stone"]],
            [3, 6, 8, ["minecraft:stone"]],
            [4, 0, 0, ["minecraft:white_wool"]],
            [4, 0, 1, ["minecraft:oxidized_cut_copper"]],
            [4, 0, 2, ["minecraft:oxidized_cut_copper"]],
            [4, 0, 3, ["minecraft:oxidized_cut_copper"]],
            [4, 0, 4, ["minecraft:oxidized_cut_copper"]],
            [4, 0, 5, ["minecraft:oxidized_cut_copper"]],
            [4, 0, 6, ["minecraft:oxidized_cut_copper"]],
            [4, 0, 7, ["minecraft:oxidized_cut_copper"]],
            [4, 0, 8, ["minecraft:oxidized_cut_copper"]],
            [4, 5, 0, ["minecraft:lantern"]],
            [4, 5, 8, ["minecraft:lantern"]],
            [4, 6, 0, ["minecraft:stone"]],
            [4, 6, 1, ["minecraft:stone"]],
            [4, 6, 7, ["minecraft:stone"]],
            [4, 6, 8, ["minecraft:stone"]]
        ],
        "requirements": []
    })
})